spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: 1234

  security:
    user:
      username: seniru
      password: 1234

  jpa:
    hibernate:
      ddl-auto: update